title: BOSS-2024
description: <b>B</b>ayesian and surr<b>O</b>gate-a<b>S</b>sisted <b>S</b>earch and Optimisation - PPSN workshop 2024
baseurl: ""
url: https://bossworkshop.github.io/

remote_theme: piazzai/jekyll-nagymaros@v1.1.0

copyright: Place Holder
indexing: true

permalink: pretty

exclude:
    - LICENSE
    - README.md
